name: "PR comment"
description: "Add comment to PR"
inputs:
    GITHUB_TOKEN:
        description: "Github token of the repository (automatically created by Github)"
        required: true
runs:
    using: "node12"
    main: "index.js"
